import path from 'node:path';
import { readText, writeAtomic } from '../io.js';
import { appendEvent, commitState } from '../store.js';
import { allEvidence } from '../evidence.js';
import { PHASE_GATE, phasePlan, questionsOf, readSpecMeta, stepsOf, verificationProblem } from '../machine.js';
import * as G from '../git.js';
import { c } from '../render.js';

const MARK_START = '<!-- timc:generated:start -->';
const MARK_END = '<!-- timc:generated:end -->';

const HANDWRITTEN = `
## Rejadan farqlar / Differences from the plan

_What ended up different from what was planned, and why. Written by a human._

## Ma'lum cheklovlar / Known limitations

_What this does not do, what was deliberately left out, what to watch for._
`;

/**
 * `timc final --render`
 * The record another engineer reads months later. Generated from durable state
 * so it cannot drift from what actually happened; only two sections are
 * hand-written, and re-rendering preserves them.
 */
export async function final({ args, ctx }) {
  if (!ctx.task) { process.stderr.write('timc final: no active task\n'); return 1; }
  const file = path.join(ctx.task.__dir, 'final.md');
  const existing = readText(file, '');
  const tail = keepHandwritten(existing);
  const body = renderFinal(ctx);
  writeAtomic(file, `${MARK_START}\n${body}\n${MARK_END}\n${tail}`);

  appendEvent(ctx.P, { type: 'FINAL_RENDERED', task: ctx.task.id, payload: { file: 'final.md' } });
  commitState(ctx, `timc: ${ctx.task.id} final rendered`);

  if (args.flags.json) { process.stdout.write(`${JSON.stringify({ file, bytes: body.length }, null, 2)}\n`); return 0; }
  if (args.flags.print) { process.stdout.write(`${body}\n`); return 0; }
  process.stdout.write([
    `${c.green('✓')} final.md render qilindi / rendered`,
    `  ${path.relative(ctx.codeRoot, file).split(path.sep).join('/')}`,
    `  ${c.dim('qo\'lda to\'ldiring / fill in by hand: "Rejadan farqlar", "Ma\'lum cheklovlar"')}`,
  ].join('\n') + '\n');
  return 0;
}

/** Keep everything after the generated block; seed it the first time. */
function keepHandwritten(existing) {
  const end = existing.indexOf(MARK_END);
  if (end === -1) return HANDWRITTEN;
  const tail = existing.slice(end + MARK_END.length).replace(/^\n+/, '');
  return tail.trim() ? `\n${tail}` : HANDWRITTEN;
}

export function renderFinal(ctx) {
  const t = ctx.task;
  const spec = readSpecMeta(t) ?? {};
  const evidence = allEvidence(ctx.P).filter((e) => !e.task || e.task === t.id);
  const commits = G.commitsWithTrailer(ctx.codeRoot, 'TIMC-Task', t.id);
  const startRef = `refs/timc/tasks/${t.id}/start`;
  const startSha = G.gitSafe(ctx.codeRoot, ['rev-parse', '--verify', '--quiet', startRef]);
  const diffStat = startSha
    ? G.gitSafe(ctx.codeRoot, ['diff', '--stat', `${startSha}..HEAD`], '')
    : null;

  const L = [];
  L.push(`# ${t.id} — ${t.title}`);
  L.push('');
  L.push(`_Generated by \`timc final --render\`. Everything above the marker comes from durable state; do not edit it._`);
  L.push('');
  L.push('| | |');
  L.push('|---|---|');
  L.push(`| Track | ${t.track} ${t.classification?.signals?.length ? `(${t.classification.signals.join(', ')})` : ''} |`);
  L.push(`| Phase | ${t.phase} |`);
  L.push(`| Created / updated | ${t.created} → ${t.updated} |`);
  L.push(`| Branch | ${t.external?.branch ?? '—'} |`);
  L.push(`| Revision | ${t.revision ?? 0} |`);
  L.push('');

  L.push('## Maqsad / Goal');
  L.push('');
  L.push(t.intent ?? t.title);
  L.push('');

  // Gates: bypassed ones stay visible. A record that hides how it was reached
  // is worse than no record.
  L.push('## Fazalar / Phases');
  L.push('');
  L.push('| phase | status | when | note |');
  L.push('|---|---|---|---|');
  for (const phase of phasePlan(t)) {
    if (phase === 'CREATED') continue;
    const g = t.gates?.[PHASE_GATE[phase]];
    const status = g?.status ?? (phase === t.phase ? 'in progress' : 'not reached');
    L.push(`| ${phase} | ${status} | ${g?.at?.slice(0, 16).replace('T', ' ') ?? '—'} | ${g?.reason ?? ''} |`);
  }
  L.push('');

  L.push('## Nima qilindi / What was built');
  L.push('');
  if (!stepsOf(t).length) L.push('_No steps recorded._');
  else {
    L.push('| step | kind | delivers | status | evidence | commits |');
    L.push('|---|---|---|---|---|---|');
    for (const s of stepsOf(t)) {
      L.push(`| ${s.id} | ${s.kind ?? 'slice'} | ${s.delivers ?? s.goal ?? ''} | ${s.status}${s.skip_reason ? ` (${s.skip_reason})` : ''} | ${(s.evidence ?? []).length}/${(s.validate ?? []).length} | ${(s.commits ?? []).join(', ') || '—'} |`);
    }
  }
  L.push('');

  const drifted = stepsOf(t).filter((s) => s.drift_accepted?.length);
  const retried = stepsOf(t).filter((s) => (s.retries ?? 0) > 0);
  if (drifted.length || retried.length) {
    L.push('### Rejadan chetga chiqishlar / Deviations recorded automatically');
    L.push('');
    for (const s of drifted) L.push(`- ${s.id}: accepted drift on ${s.drift_accepted.join(', ')}`);
    for (const s of retried) L.push(`- ${s.id}: ${s.retries} retry(ies)${s.fail_reason ? ` — last: ${s.fail_reason}` : ''}`);
    L.push('');
  }

  L.push('## Qarorlar / Decisions');
  L.push('');
  const decisions = Array.isArray(t.decisions) ? t.decisions : [];
  if (!decisions.length) L.push('_None recorded._');
  else {
    L.push('| id | type | decision | by | evidence |');
    L.push('|---|---|---|---|---|');
    for (const d of decisions) {
      L.push(`| ${d.id} | ${d.type} | ${d.decision} | ${d.decision_maker} | ${d.evidence ?? '—'} |`);
    }
  }
  L.push('');

  const answered = questionsOf(t).filter((q) => q.answer);
  if (answered.length) {
    L.push('## Interview — nima aniqlandi / what was settled');
    L.push('');
    for (const q of answered) {
      L.push(`- **${q.id}** ${q.question}`);
      L.push(`  - javob / answer: ${q.answer}${q.evidence ? ` _(${q.evidence})_` : ''}`);
      if (q.recommendation && q.recommendation !== q.answer) L.push(`  - tavsiya edi / was recommended: ${q.recommendation}`);
    }
    L.push('');
  }

  const acs = Array.isArray(spec.acceptance_criteria) ? spec.acceptance_criteria : [];
  if (acs.length) {
    L.push('## Qabul mezonlari / Acceptance criteria');
    L.push('');
    for (const ac of acs) {
      const v = t.verifications?.[ac.id];
      const ok = !verificationProblem(ctx, t, ac.id);
      const note = v?.waived ? ` _(waived by ${v.by}: ${v.reason})_` : v?.evidence ? ` _(${v.step}: ${v.evidence})_` : '';
      L.push(`- ${ok ? (v?.waived ? '[~]' : '[x]') : '[ ]'} **${ac.id}** — ${ac.text}${note}`);
    }
    L.push('');
  }
  const seams = Array.isArray(spec.seams) ? spec.seams : [];
  if (seams.length) {
    L.push('## Seams');
    L.push('');
    for (const s of seams) {
      const a = t.approvals?.seams?.[s.id];
      L.push(`- **${s.id}** ${s.where} — ${s.kind}${a ? ` (approved by ${a.by}${a.quote ? `, events#seq=${a.quote}` : ''})` : ''}`);
    }
    L.push('');
  }

  L.push('## Tekshiruv / Testing performed');
  L.push('');
  if (!evidence.length) L.push('_No evidence recorded._');
  else {
    const byCommand = new Map();
    for (const e of evidence) {
      const key = e.command;
      const prev = byCommand.get(key) ?? { runs: 0, lastExit: null, lastAt: null };
      byCommand.set(key, { runs: prev.runs + 1, lastExit: e.exit, lastAt: e.recordedAt ?? e.startedAt });
    }
    L.push('| command | runs | last exit | last run |');
    L.push('|---|---|---|---|');
    for (const [cmd, v] of byCommand) L.push(`| \`${cmd}\` | ${v.runs} | ${v.lastExit} | ${String(v.lastAt ?? '').slice(0, 16).replace('T', ' ')} |`);
  }
  L.push('');

  L.push('## Kod / Code');
  L.push('');
  L.push(`- commits carrying \`TIMC-Task: ${t.id}\`: ${commits.length ? commits.map((s) => s.slice(0, 8)).join(', ') : '—'}`);
  if (diffStat) {
    L.push('');
    L.push('```');
    L.push(diffStat.split('\n').slice(-25).join('\n'));
    L.push('```');
  } else {
    L.push(`- _no start ref (${startRef}); diff range unknown_`);
  }
  L.push('');

  const openQ = questionsOf(t).filter((q) => !q.answer);
  if (openQ.length) {
    L.push('## Ochiq qolgan savollar / Still open');
    L.push('');
    for (const q of openQ) L.push(`- **${q.id}** ${q.question}`);
    L.push('');
  }

  return L.join('\n');
}

export default final;
